#!/usr/bin/env python3
#-*- coding:utf8  -*-
# __author__ = "Auther"
# Date : 2018/9/21
'''

'''
import socket
import time


sk = socket.socket()
print(sk)
address = ('127.0.0.1',8000)
sk.bind(address)
sk.listen(1)  #建立链接保持的数量，0可以建立1个链接
print('watting...')
while True:
    conn,addr = sk.accept()             # accept接收得对象是一个元组，两个元素，所以用两个变量去接收
    print(addr)

    while True:
        T = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
        try:
            data = conn.recv(1024)
        except Exception as e:
            break

        print('.........',str(data,'utf8'))
        inp = input('>>>')
        conn.send(bytes(inp,'utf8'))

sk.close()

# while True:
#     data = conn.recv(1024)
#     T = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
#     print(T)
#     print('........',str(data,'utf8'))
#     if not data:break
#     inp = input('>>>')
#     conn.send(bytes(inp, 'utf8'))
# sk.close()
